### ISSUE TITLE
Refs

### ISSUE THREAD

**Issue by jridgewell** [jridgewell/babel-plugin-incremental-dom#27]
React has the concept of [Refs](https://facebook.github.io/react/docs/more-about-refs.html) that allow you to directly reference a node in the View:

```jsx
{
  render: function() {
    return <input ref="key" />;
  },
  componentDidMount: function() {
    this.refs.input.focus();
  }
}
```

This seems analogous to using a `key` in iDOM:

```js
var refs = {};
refs['key'] = elementVoid('input', 'key');

// somehow return refs, or attach it to `this`
```

- Components instances are attached as the ref. DOM nodes are attached as the ref otherwise
- Ref may be a callback, which is passed the node as a parameter

**Comment by thejameskyle** [comment]
This is getting to the point where I'd recommend building an additional library on top of idom that would give you hooks for framework-y things like this.

**Comment by jridgewell** [comment]
Can you give an example of what you mean?

**Comment by thejameskyle** [comment]
Something that can wrap a group of idom as a "component" so things like refs make sense, it could also just be a standard interface that is defined. But also simple enough that it is flexible for different APIs.

I imagine calling a separate API that wraps idom methods that can be captured by this library.

```js
<div ref="myRef"></div>
// becomes
ComponentLib.elementOpen('div', null, ['ref', 'myRef']);
ComponentLib.elementClose('div');
```

Which can be used inside of:
```js
var MyComponent = ComponentLib.createComponent(function() {
  ComponentLib.elementOpen('div', null, ['ref', 'myRef']);
  ComponentLib.elementClose('div');
});

var myComponent = new MyComponent();
myComponent.render();
myComponent.refs.myRef === `<div></div>`
```
