### ISSUE TITLE
Limitations in rendering

### ISSUE THREAD

**Issue by nasushkov** [jridgewell/babel-plugin-incremental-dom#37]
Hi, I played a little with babel-plugin-incremental-dom and faced some problems in rendering. I'm just curious if I did something wrong or some things just not supported. 
1. I get correct rendering only when all functions are defined in the scope of the main rendering function. For example, this code renders well: 
`function renderMain() {
     const renderInput = () => (
        <div>
            <input type="text" id="testInput"/>           
        </div>
    );
    return (
        <div id="app">
            {renderInput()}           
        </div>
    );
}` 
At the same time, if we define renderInput outside of  the scope of renderMain we'll get some additional metadata rendered as plain text. 
2. It seems that conditional statements for main render method are not supported. So, this will not work:
`function renderMain(flag) {
     if(flag){
         return (
        <div id="app">           
        </div>
    );
     }
    return (
        <div id="app">
            {renderInput()}           
        </div>
    );
}`

**Comment by dwiyatci** [comment]
Seems like I got the same issue +1

**Comment by jridgewell** [comment]
I'll take a look into this tonight. Thanks for bringing up more cases!

**Comment by jridgewell** [comment]
[Fixed](https://github.com/jridgewell/babel-plugin-incremental-dom/commit/e5229ed8dd55501563f7e9d88e60d75f01e96069) the first issue, we were recursively calling `_renderArbitrary` on the DOM node, which is was wrong.

**Comment by gabrielhpugliese** [comment]
Hi @jridgewell, could you publish that fix on npm? I tried to install from master branch but it seems that npm doesn't build it and raises errors when trying to transpile with webpack :crying_cat_face: If you need any help to test or something else I'm right here.

**Comment by jridgewell** [comment]
Both fixes should be out in v3.0.2.

**Comment by gabrielhpugliese** [comment]
Thanks!

**Comment by nasushkov** [comment]
Thank you, Justin!
