### ISSUE TITLE
Boolean attributes bug

### ISSUE THREAD

**Issue by dwiyatci** [jridgewell/babel-plugin-incremental-dom#38]
I stumbled upon this issue yesterday when trying to render `checked` attribute of `input` element:

```javascript
function renderCheckbox() {
  const flag = false;

  return (
    <input type="checkbox" checked={flag} />
  );
}
```

I would expect this to be rendered in the DOM:

`<input type="checkbox" />`

but instead, what I found is: 

`<input type="checkbox" checked="false" />`

which, of course, **always** made the checkbox checked. :astonished: 

A bug?

**Comment by jridgewell** [comment]
That's actually a iDOM [bug](https://github.com/google/incremental-dom/issues/198). :frowning:

**Comment by dwiyatci** [comment]
Ouch, okay then. :sweat_smile:

Currently I have a workaround like so (maybe it will be useful for others, too - at least for the moment):

```javascript
function renderCheckbox(checked) {

  /**
   * HACK: A workaround for a iDOM bug.
   * @see https://github.com/jridgewell/babel-plugin-incremental-dom/issues/38
   * @see https://github.com/google/incremental-dom/issues/198
   */
  const booleanAttrs = {};
  if (checked) {
    booleanAttrs.checked = '';
  }

  return (
    <input type="checkbox" {...booleanAttrs} />
  );
}
```

Quite nasty, but it appears to be working.  :-)

**Comment by jridgewell** [comment]
You should be able to use:

```jsx
<input type="checkbox" checked={checked ? true : undefined} />
```

Or for golfing:

```jsx
<input type="checkbox" checked={checked || undefined} />
```

**Comment by dwiyatci** [comment]
Wow, that indeed much clearer solution. Thanks for the hint, mate! :+1:
