### ISSUE TITLE
Bug when using an object as a key.

### ISSUE THREAD

**Issue by buzinas** [jridgewell/babel-plugin-incremental-dom#39]
It works greatly if I don't pass any key:

![no-key](https://cloud.githubusercontent.com/assets/7298695/13780678/3e65757a-ea9f-11e5-853e-ce6240d53290.png)

It works OK if I pass a value as a key (string, number):

![value-key](https://cloud.githubusercontent.com/assets/7298695/13780721/71e1982a-ea9f-11e5-9bf5-3556d6cff49d.png)

But it bugs when passing an object as a key:

![object-key](https://cloud.githubusercontent.com/assets/7298695/13780783/b0d0efa4-ea9f-11e5-8c01-93e5b7fe69a9.png)

Looking at the last image, you'll see that it rendered only one item. The curious fact is that when query-selecting the item, its key is the first object of my collection.

**Comment by buzinas** [comment]
Just tested with vanilla idom, and the error is the same, so it isn't an error of this plugin.

I'll migrate this issue to their repository. Sorry for the inconvenience.

**Comment by buzinas** [comment]
Opened https://github.com/google/incremental-dom/issues/215, thanks!

**Comment by jridgewell** [comment]
Can you post your JSX code for the screenshots you sent? The built code is super inefficient, and I've been wanting to work on a "fast-path" option that'll make it way better.

**Comment by buzinas** [comment]
Sure:

```jsx
  render() {
    let selectingDiv;

    if (this.isSelecting) {
      const {startY, startX, endY, endX} = this.selectingPosition;

      const top = Math.min(startY, endY);
      const height = Math.max(startY, endY) - top;
      const left = Math.min(startX, endX);
      const width = Math.max(startX, endX) - left;

      selectingDiv = <div class='dl-exp--selecting' style={`top: ${top}px; left: ${left}px; height: ${height}px; width: ${width}px;`}></div>;
    }
    return (
      <div class='dl-exp'>
        <div class='dl-exp__field'>
          <label>Filtro <input type='text' oninput={(e) => this.textChanged(e.target.value)} /></label>
        </div>
        <ul class='dl-exp__container'>
          {
            this.filteredFiles.map(file => {
              const title = `${file.size} - ${file.date.toLocaleString()}`;
              const className = `dl-exp__${file.type}${file.selected ? ' selected' : ''}`;

              return <li key={file.fullName} file={file} title={title} class={className} onclick={(e) => this.fileClicked(e, file)} ondblclick={(e) => this.fileDblClicked(e, file)}>{file.name}</li>
            })
          }
        </ul>
        {selectingDiv}
      </div>
    );
  }
```
