### ISSUE TITLE
Usage of incremental dom's statics

### ISSUE THREAD

**Issue by mairatma** [jridgewell/babel-plugin-incremental-dom#48]
Hi there!

First of all I just wanted to thank you for this awesome project, it's been really helpful for me :D

I've been using it a lot, and I've noticed a behavior that is a bit weird. Let's say you have code similar to this:

```javascript
function render(foo) {
  var el;
  if (foo) {
    el = <div class="foo" id="Foo" data-sth="2">Foo</div>;
  } else {
    el = <div class="bar" id="Bar" data-sth="3">Bar</div>;
  }
  return <div class="wrapper">{el}</div>;
}
```

If I render with `foo = true` and then repatch with `foo = false`, no attributes will be updated. I checked the compiled code and saw that it's because **babel-plugin-incremental-do** compiles attributes declared without variables like this to use incremental dom's `statics` optimization.

I see how that may makes sense in some cases, but I think that cases like the one I showed should work as expected, specially since developers using the jsx won't necessarily know that this is using statics, and how that even works inside incremental dom.

Even if statics aren't removed entirely from the compilation, it'd be nice to at least only use it when the element has an explicit `key` set. That's what incremental dom's docs [advises](http://google.github.io/incremental-dom/#rendering-dom/statics-array), due to cases like this. At least that way people may notice more quickly that this may be happening due to the `key`, and will avoid most problems.

**Comment by jridgewell** [comment]
There's an iDOM [issue](https://github.com/google/incremental-dom/issues/150) about this as well. I'm slowly pushing him to use statics as an [immutable pair](https://github.com/google/incremental-dom/blob/master/src/virtual_elements.js#L76-L78) of the key, too.

In the mean time, I could definitely see this as a runtime flag to enable statics without a key. Want to work on a PR?

**Comment by mairatma** [comment]
Sure! Thanks for being open to suggestions like this :) And also agree that it should be taken in consideration together with key.

I won't have time to work on this today, but on Monday at most I can send something to you.

**Comment by jridgewell** [comment]
Re: https://github.com/jridgewell/babel-plugin-incremental-dom/commit/9db682c78732682c022a32077dc499a98c9f4bb7.

I decided to instead generate a UUID v4 `key` (still uses the same `forceStatics` option). That should avoid the problem entirely, without deopting the `statics` array.

```js
// Disabled (default)
function render(condition) {
  elementVoid("a", "key", ["href", "http://key/specified"]);
  if (condition)
    elementVoid("a", null, null, "href", "http://example.com");
  } else {
    elementVoid("a", null, null, "href", "http://other.com");
  }
}
```

```js
// Enabled
function render() {
  elementVoid("a", "key", ["href", "http://key/specified"]);
  if (condition)
    elementVoid("a", "8ad02822-f391-48fb-a277-8065f7f92a99", ["href", "http://example.com"]);
  } else {
    elementVoid("a", "adbe4414-e6ad-41c0-aae2-1ca578653119", ["href", "http://other.com"]);
  }
}
```
