### ISSUE TITLE
Using JSX gives error

### ISSUE THREAD

**Issue by anonrig** [jridgewell/babel-plugin-incremental-dom#50]
I've this rendering function and it throws an error somewhere inside this function as: 

`Uncaught TypeError: Cannot read property 'firstChild' of null`

In incremental-dom-cjs.js file at line 750

```
function renderTodoItem(todo) {
    return (
      <li class="list-item todo-item todo-item-{todo.done ? 'done' : 'open'}">
        <label class="label-checkbox">
          <input class="checkbox js_toggle_todo" type="checkbox" data-id="{todo.id}"  />
          <p class="{todo.priority.toLowerCase()}">{todo.text}</p>
          <span>{todo.priority}</span>
        </label>
      </li>
    );
}
````

**Comment by jridgewell** [comment]
The output I'm getting is

```js
"use strict";

var _hasOwn = Object.prototype.hasOwnProperty;

var _forOwn = function _forOwn(object, iterator) {
  for (var prop in object) {
    if (_hasOwn.call(object, prop)) iterator(object[prop], prop);
  }
};

var _renderArbitrary = function _renderArbitrary(child) {
  var type = typeof child;

  if (type === "number" || type === "string" || child && child instanceof String) {
    text(child);
  } else if (type === "function" && child.__jsxDOMWrapper) {
    child();
  } else if (Array.isArray(child)) {
    child.forEach(_renderArbitrary);
  } else if (String(child) === "[object Object]") {
    _forOwn(child, _renderArbitrary);
  }
};

function renderTodoItem(todo) {
  elementOpen("li", null, null, "class", "list-item todo-item todo-item-{todo.done ? 'done' : 'open'}");
  elementOpen("label", null, null, "class", "label-checkbox");
  elementVoid("input", null, null, "class", "checkbox js_toggle_todo", "type", "checkbox", "data-id", "{todo.id}");
  elementOpen("p", null, null, "class", "{todo.priority.toLowerCase()}");

  _renderArbitrary(todo.text);

  elementClose("p");
  elementOpen("span");

  _renderArbitrary(todo.priority);

  elementClose("span");
  elementClose("label");
  return elementClose("li");
}
```

Which is correct for what you've pasted. Also, you've got string interpolation issues (`{todo.done ? 'done' : 'open'}` and `{todo.priority.toLowerCase()}` are literal strings, not template literals).

Also, the error message you've included means this is coming from iDOM, not the JSX->iDOM conversion, likely meaning it's how you are calling this `renderTodoItem`. Mind posting that?

**Comment by anonrig** [comment]
@jridgewell Thank you for your fast reply.

Let me give you a more new version:

```
export function reRenderList(el, state) {
  let todoItems = state.todos;

  if (state.filter == 'SHOW_ALL')
    todoItems = todoItems;
  else if (state.filter == 'SHOW_OPEN')
    todoItems = todoItems.filter(todo => !todo.done)
  else
    todoItems = todoItems.filter(todo => todo.done)

  patch(el, () => {
    todoItems.map((todo) => {
      const todoClass = 'todo-item todo-item-' + todo.done ? 'done' : 'open';

      return (
        <li class={todoClass}>
          <label class="label-checkbox">
            <input class="checkbox js_toggle_todo" type="checkbox" data-id={todo.id} checked={todo.done} />
            <p class={todo.priority.toLowerCase()}>{todo.text}</p>
            <span>{todo.priority}</span>
          </label>
        </li>
      )
    });
  });
}
```

When I remove `{todo.text}` and `{todo.priority}` from the template, it works like a charm, but when I add it: it gives this problem again:

actions.js:41 Uncaught ReferenceError: text is not defined

My actions.js:

```
export function addTodo(text) {
    return {
        type: ADD_TODO,
        text
    }
} -> THIS IS THE LINE 41

```

**Comment by anonrig** [comment]
For todo.text

```
if (type === "number" || type === "string" || child && child instanceof String) {
```

This validation fails, even though, todo.text is a String.

```
todo.text
-> "Take a look at the application"
todo.text instanceof String
-> false
todo.text === 'string'
-> false
```

**Comment by jridgewell** [comment]
A few things:

1. `const todoClass = 'todo-item todo-item-' + todo.done ? 'done' : 'open';`.
  - This doesn't behave like it reads, it'll only return `'done'` every time. Try `'todo-item todo-item-' + (todo.done ? 'done' : 'open')`
2. better approach like `typeof child == "string"`.
  - That's the `type === 'string'` check in the conditional.
- `actions.js:41 Uncaught ReferenceError: text is not defined`.
  - That's because you've not imported iDOM's `text` function. The `{todo.text}` requires the use of `renderArbitrary`, which eventually tries to call `text`:

    ```
    if (type === "number" || type === "string" || child && child instanceof String) {
        text(child);
    }
   ```

**Comment by anonrig** [comment]
I've added

```
import { text } from 'incremental-dom'
```
to the file but only this change will fix it on my case

```
const text = require('incremental-dom).text;
```

**Comment by jridgewell** [comment]
Ooo, that's a bug. Babel won't remap `text` calls to the imported reference.

**Comment by Tiendq** [comment]
This bug still exist, with very simple case.

It won't work, causes same original error (`Uncaught TypeError: Cannot read property 'firstChild' of null`):

```
let todoItems = items.map(x => <li>x.text</li>);
patch(container, () => {todoItems});
```

It works, no error, if use map directly:

`patch(container, () => {items.map(x => <li>x.text</li>)});`

**Comment by jridgewell** [comment]
@Tiendq, that's a separate issue, and one I can't fix. The plugin can't know that `items.map` will execute the function the `<li>`s are in, or that you're `patch`'s renderer is the real root of the render.

**Comment by Tiendq** [comment]
Thanks, so is there a work-around? or I can't simply use `map` this way.

**Comment by jridgewell** [comment]
You can't pre-evaluate nodes and have them rendered inline like this. You can, however, include them in a root node:

```js
function todoItems() {
  let todoItems = items.map(x => <li>x.text</li>);
  return <ul>{todoItems}</ul>
}
patch(container, () => {todoItems});
```

Or, you can evaluate them later:

```js
function todoItems() {
  return items.map(x => <li>x.text</li>);
}
patch(container, () => {todoItems()});

**Comment by Tiendq** [comment]
It works like a charm, thank you.
