### ISSUE TITLE
Input conditional check fails

### ISSUE THREAD

**Issue by anonrig** [jridgewell/babel-plugin-incremental-dom#53]
Adding a similar input like this fails.

```
<input id={filter} class="js_toggle_radio" type="radio" name="statusFiltering" data-id={filter} checked={(state.filter == filter)} />
```

React actually understands the boolean value inside an checked attribute, and automatically inserts checked if  the boolean is true. But in our case, using JSX with incremental-dom actually adds `checked="true"` and `checked="false"` which creates an anomaly. According to W3C specs, only the `checked` attribute should be added if you want it to be checked.

Example use case:

```
<input id={filter} class="js_toggle_radio" type="radio" name="statusFiltering" data-id={filter} {(state.filter == filter ? 'checked' : '')} />
```

This fails due to compiler.

**Comment by jridgewell** [comment]
This is an [upstream issue](https://github.com/google/incremental-dom/issues/239) with iDOM.
