### ISSUE TITLE
Error is thrown when using "xlink:href" attribute in svgs

### ISSUE THREAD

**Issue by mairatma** [jridgewell/babel-plugin-incremental-dom#54]
When trying to compile jsx that uses the `xlink:href` attribute I get a weird error saying that `JSX Namespaces aren't supported`.

For example, when compiling this jsx:

```javascript
return <svg>
   <use xlink:href="" />
</svg>;
```

I get this:
<img width="868" alt="screen shot 2016-05-23 at 6 08 17 pm" src="https://cloud.githubusercontent.com/assets/5216049/15484655/6443177c-2111-11e6-8aa8-48b00f36b813.png">

This time I don't have an idea of what's causing this, so just reporting for now.

**Comment by jridgewell** [comment]
We throw that [during](https://github.com/jridgewell/babel-plugin-incremental-dom/blob/master/src/index.js#L41-L43) element traversal. At the time, iDOM didn't support any namespaces and neither did React, so I just disabled them completely.

**Comment by jridgewell** [comment]
Working on this in the [namespace-attributes](https://github.com/jridgewell/babel-plugin-incremental-dom/compare/namespace-attributes?expand=1) branch. Just need to write docs.

I'm going to keep this behind a flag since React doesn't support this.

**Comment by jridgewell** [comment]
Out with v3.3.0.
